package com.aepl.atcu.locators;

import org.openqa.selenium.By;

public class MyAis140TicketsPageLocators {
    public static final By navBarLink = By.xpath("//span[@class=\"headers_custom color_3D5772\"]");
    public static final By MyAis140 = By.xpath("//*[@id=\"navbarSupportedContent\"]/div/ul/li[2]/div/a[1]");
    public static final By SearchBox = By.xpath("/html/body/app-root/app-my-ais140-ticket-page/div/div[1]/div[4]/div/div[1]/i/div/input");
    public static final By tableHeadings = By.xpath("//tr[@class=\\\"text-center\\\"]");
    public static final By overlay = By.cssSelector(".overlay");
    public static final By viewButton = By.xpath("//*[@id=\"DataTables_Table_0\"]/tbody/tr/td[12]/mat-icon");
    public static final By Arrow = By.xpath("//div[@class=\"thumb ng-star-inserted\"]");
    public static final By TicketNumber = By.id("mat-input-22");
    public static final By TicketCreate = By.id("mat-input-23");
    public static final By TicketAssigned = By.id("mat-input-24");
    public static final By TicketCompleted = By.id("mat-input-25");
    public static final By TicketCertificate = By.id("mat-input-26");
    public static final By TicketStatus = By.id("mat-input-27");
    public static final By TicketRemark = By.id("mat-input-28");
    public static final By TicketGenrate = By.id("mat-input-29");
    public static final By TicketDesc = By.id("mat-input-30");
    public static final By DeviceInfo = By.className("crm_head_b");
    public static final By UINNumber = By.id("mat-input-31");
    public static final By IMEINumber = By.id("mat-input-32");
    public static final By ICCIDNumber = By.id("mat-input-33");
    public static final By DeviceModel = By.id("mat-input-34");
    public static final By DeviceMake = By.id("mat-input-35");
    public static final By primaryOperatorName = By.id("mat-input-36");
    public static final By primaryOperatorNumber = By.id("mat-input-37");
    public static final By secondaryOperatorName = By.id("mat-input-38");
    public static final By secondaryOperatorNumber = By.id("mat-input-39");
    public static final By vehicleOwnerName = By.id("mat-input-40");
    public static final By vehicleOwnerMobileNumber = By.id("mat-input-41");
    public static final By vehicleOwnerPOAdocname = By.id("mat-input-42");
    public static final By vehicleOwnerPOAdocnumber = By.id("mat-input-43");
    public static final By vehicleOwnerPOIdocname = By.id("mat-input-44");
    public static final By vehicleOwnerPOIdocnumber = By.id("mat-input-45");
    public static final By vehicleOwnerAddress = By.id("mat-input-46");
    public static final By vehiclemodel = By.id("mat-input-47");
    public static final By vehiclemake = By.id("mat-input-48");
    public static final By manufacturingyear = By.id("mat-input-49");
    public static final By chassisnumber = By.id("mat-input-50");
    public static final By enginenumber = By.id("mat-input-51");
    public static final By registrationnumber = By.id("mat-input-52");
    public static final By invoicedate = By.id("mat-input-53");
    public static final By invoicenumber = By.id("mat-input-54");
    public static final By rtostate = By.id("mat-input-55");
    public static final By rtocode = By.id("mat-input-56");
    public static final By ignstatus = By.id("mat-input-57");
    public static final By ignButton = By.xpath("/html/body/app-root/app-my-activations-details-page/div/form/div/div[5]/div/div[2]/div[23]/button");
    public static final By dealercode = By.id("mat-input-58");
    public static final By dealeremail = By.id("mat-input-59");
    public static final By dealercity = By.id("mat-input-60");
    public static final By dealerphoneno = By.id("mat-input-61");
    public static final By posname = By.id("mat-input-62");
    public static final By poscode = By.id("mat-input-63");
    public static final By fotabatchid = By.id("mat-input-64");
    public static final By currentfw = By.id("mat-input-65");
    public static final By assinedfw = By.id("mat-input-66");
    public static final By fotastatus = By.id("mat-input-67");
    public static final By fotaprogress = By.id("mat-input-68");
    public static final By fotapriip = By.id("mat-input-69");
    public static final By fotapriipstatus = By.id("mat-input-70");
    public static final By fotasecip = By.id("mat-input-71");
    public static final By fotasecipstatus = By.id("mat-input-72");
    public static final By stateenableota = By.id("mat-input-73");
    public static final By Reason2skipstage = By.id("mat-select-value-23");
    public static final By Remark2skipstage = By.id("mat-input-75");
    public static final By skippedby = By.id("mat-input-74");
    public static final By selectskipstage2 = By.id("mat-option-190");
    public static final By removestage2restriction = By.xpath("/html/body/app-root/app-my-activations-details-page/div/form/div/div[7]/div/div[2]/div[25]/div[4]/button");
    public static final By VehicleIgnitionOn = By.xpath("//*[@id=\"mat-select-value-1\"]");
    public static final By VehicleIgnitionOnOption = By.xpath("//*[@id=\"mat-option-15\"]/span");
    public static final By Remarkforsubstage1 = By.id("mat-input-2");
    public static final By overallticketstatus = By.xpath("//*[@id=\"mat-select-18\"]/div/div[2]/div");
    public static final By inprogressstatus = By.xpath("//*[@id=\"mat-option-146\"]/span");
    public static final By updatebutton = By.xpath("/html/body/app-root/app-my-activations-details-page/div/form/div/div[8]/div/div[2]/div[61]/button");
    public static final By gsmnw = By.id("mat-select-value-3");
    public static final By gsmnwoption = By.xpath("//*[@id=\"mat-option-33\"]/span");
    public static final By Remarkforsubstage2 = By.id("mat-input-4");
    public static final By gpsfix = By.xpath("//*[@id=\"mat-select-4\"]/div/div[2]/div");
    public static final By gpsfixoption = By.xpath("//*[@id=\"mat-option-51\"]/span");
    public static final By Remarkforsubstage3 = By.id("mat-input-6");
}

